
TrainMethod: RND
EnvType: ddave
EnvID: ddave
MaxStepPerEpisode: 45 #4500
ExtCoef: 2.
LearningRate: 1.0e-4
NumEnv: 1
NumStep: 10 #128
Gamma: 0.999
IntGamma: 0.99
Lambda: 0.95
StableEps: 1.0e-8
StateStackSize: 4
PreProcHeight: 84
ProProcWidth: 84
UseGAE: True
UseGPU: False
UseNorm: False
UseNoisyNet: False
ClipGradNorm: 0.5
Entropy: 0.001
Epoch: 4
MiniBatch: 4
PPOEps: 0.1
IntCoef: 1.
StickyAction: True
ActionProb: 0.25
UpdateProportion: 0.25
LifeDone: False
ObsNormStep: 50


